version: "3"

services:
  web:
    build: .
    container_name: web
    restart: "always"
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    env_file:
      - .env
    command:
      python manage.py runserver 0.0.0.0:8000