from django.test import TestCase

from model_bakery import baker
from rest_framework_simplejwt.authentication import JWTAuthentication

from users.models import User
from users.utils import get_token_for_user


class UtilsTests(TestCase):
    def setUp(self):
        self.user = baker.make(User)

    def test_get_token_for_user(self):
        """Checks access token generated by get_token_for_user()"""
        token = get_token_for_user(self.user)
        validated_token = JWTAuthentication().get_validated_token(token)
        token_user = JWTAuthentication().get_user(validated_token)

        self.assertEqual(
            self.user,
            token_user,
            msg="""Wrong User for token {}. Expected: {}. Obtained: {}."""
            .format(token, self.user, token_user)
        )
